### model
model_name_or_path: models/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1

### dataset
dataset: my_dataset
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: saves/qwen2.5-7b-Instruct/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true


### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 5e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true   
ddp_timeout: 180000000


### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### eval
# val_size: 0.1
# do_eval: true
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
# compute_metrics: examples/metrics/my_metrics.py
